### PR TITLE
split the user_story into two different versions, one for rent, the other one for sublet

### PR DESCRIPTION
**Pull request by ericqiangguo**
hi, guys, here are the two split user stories for rent and for sublet. Sorry for the late of renewing.  Please let me know if there are some comments.

### CODE REVIEW

**Comment by xingweitian** [comment]
Is it necessary to name user story folder "user_story_split"? I think it's better to just call it "user_story".

**Comment by lyuboxin** [comment]
I am wondering is it better to use the last PR instead of creating a new one. You can modify files on the branch feature/user_story that will make PR updated automatically.

**Comment by ericqiangguo** [comment]
> Is it necessary to name user story folder "user_story_split"? I think it's better to just call it "user_story".

Is that means I need to combine the split user_story_rent.md and user_story_sublet.md with the already existed branch "feature/user_story"?

**Comment by zhangjiangqige** [comment]
We should reuse the previous PR #9 . Just push new commits in this branch to the previous branch. I'm closing this PR.

And yes we should keep using `user_story` as the folder name, and use more specific names for the files, e.g. `rent_a_room.md` and `sublet_a_room.md`.

**Comment by ericqiangguo** [comment]
> I am wondering is it better to use the last PR instead of creating a new one. You can modify files on the branch feature/user_story that will make PR updated automatically.

thanks for your comment. I will try it soon.

**Comment by ericqiangguo** [comment]
> We should reuse the previous PR #9 . Just push new commits in this branch to the previous branch. I'm closing this PR.
> 
> And yes we should keep using `user_story` as the folder name, and use more specific names for the files, e.g. `rent_a_room.md` and `sublet_a_room.md`.

thanks for your instruction, i will try it soon.

**Pull request closed without merging**
